import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";
import { AuthContextProvider } from "./Context/auth.context";
import { EventContextProvider } from "./Context/event.context";
import { DropDownContextProvider } from "./Context/dropdown.context";
import { BookingContextProvider } from "./Context/booking.context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthContextProvider>
          <EventContextProvider>
            <DropDownContextProvider>
              <BookingContextProvider>
                <div>
                  <Navbar />
                  <main className="flex-grow">{children}</main>
                  <Toaster />
                </div>
              </BookingContextProvider>
            </DropDownContextProvider>
          </EventContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
